import { ApiField, ComplexType } from '@opra/common';
import { Column, DataType, PrimaryKey } from '@sqb/connect';

@ComplexType({
  abstract: true,
  description: 'Base Record schema'
})
export class Record {

  @ApiField()
  @Column({dataType: DataType.INTEGER, notNull: true, autoGenerated: 'increment'})
  @PrimaryKey()
  _id: number;

  @ApiField()
  @Column()
  deleted?: boolean;

  @ApiField()
  @Column()
  createdAt: Date;

  @ApiField()
  @Column()
  updatedAt?: Date;

}
