command:
  publish:
    contents: build
  version:
    unified: true
  run:
    parallel: lint,clean,compile

logLevel: info

packages:
  "@opra/angular":
    dependencies:
      - "@opra/node-client"
