#file: noinspection YAMLSchemaValidation
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.2.1

workflows:
  main:
    jobs:
      - test:
          version: '18.17'
          filters:
            branches:
              only:
                - main
      - test:
          version: '20.5'
          filters:
            branches:
              only:
                - main

jobs:
  test:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/node:<< parameters.version >>
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: mongo:4.1.13
        environment:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms500m -Xmx500m
          xpack.security.enabled: false
    environment:
      NODE_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      NODE_OPTIONS: "--max-old-space-size=8192"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: sudo npm install -g npm
      - run: npm install
      - run: npm run citest
      - run: npm install coveralls --no-save
      # - coveralls/upload:
      #    coverage_file: ./coverage/lcov.info
