export const KAFKA_DEFAULT_GROUP = 'default';
export const KAFKA_OPERATION_METADATA = 'KAFKA_OPERATION_METADATA';
export const KAFKA_OPERATION_METADATA_RESOLVER =
  'KAFKA_OPERATION_METADATA_RESOLVER';
