import { ApiField, ComplexType } from '@opra/common';
import { Column, DataType, PrimaryKey } from '@sqb/connect';

@ComplexType({
  abstract: true,
  description: 'Abstract Record Model',
})
export class Record {
  @ApiField({ readonly: true })
  @Column({ dataType: DataType.INTEGER, autoGenerated: 'rowid' })
  @PrimaryKey()
  id: number;

  @Column()
  @ApiField()
  deleted?: boolean;
}
