import * as console from 'node:console';
import * as fs from 'node:fs';
import path from 'node:path';
import * as process from 'node:process';
import { getStackFileName } from '@opra/common';
import colors from 'ansi-colors';
import { program } from 'commander';
import { TsGenerator } from './ts-generator/ts-generator.js';

const dirname = path.dirname(getStackFileName());
const pkgJson = JSON.parse(
  fs.readFileSync(path.resolve(dirname, '../package.json'), 'utf-8'),
);

program
  .version(pkgJson.version)
  .argument('<serviceUrl>', 'OPRA service url')
  .argument('<outDir>', 'Output directory')
  .option('--ext', 'Adds js extension to imports')
  .option('--refns', 'Exports references with namespaces')
  .option('--no-color', 'Disables colors in logs messages')
  .action(async (serviceUrl, outDir, options) => {
    if (!options.color) colors.enabled = false;
    const generator = new TsGenerator({
      serviceUrl,
      logger: console,
      outDir,
      importExt: options.ext,
      referenceNamespaces: options.refns,
      fileHeader: `/* Generated by OPRA Code Generator, Version ${pkgJson.version} */`,
    });
    await generator
      .generate()
      .then(() => console.log(colors.greenBright('Completed')))
      .catch(e => console.error(e.message));
  });

if (process.argv.length < 3) program.help();
else program.parse(process.argv);
