import chalk from 'chalk';
import { program } from 'commander';
import * as console from 'console';
import * as fs from 'fs';
import path from 'path';
import * as process from 'process';
import { OpraHttpClient } from '@opra/node-client';
import { deleteFiles } from './oprimp/delete-files.js';
import { generateService } from './oprimp/generate-service.js';
import { getCallerFile } from './utils/get-caller-file.util.js';

const pkgJson = JSON.parse(fs.readFileSync(path.resolve(path.dirname(getCallerFile()), '../package.json'), 'utf-8'));

program
    .version(pkgJson.version)
    .argument('<serviceUrl>', 'OPRA service url')
    .argument('<outDir>', 'Output directory')
    .option('--no-color', 'Disables colors in logs messages')
    .option('-e, --extension <extension>', 'File extensions of imports')
    .action(async (serviceUrl, outDir, options) => {
      if (!options.color)
        chalk.level = 0;
      console.log(chalk.yellow('Fetching service metadata from'), chalk.whiteBright(serviceUrl));
      const client = await OpraHttpClient.create(serviceUrl);
      const metadata = client.metadata;
      console.log(chalk.yellow('Retrieved service info:'),
          chalk.whiteBright(metadata.info.title), '-',
          chalk.whiteBright(metadata.info.version));
      console.log(chalk.yellow('Removing old files..'));
      deleteFiles(outDir);

      await generateService({
        serviceUrl,
        document: metadata,
        outDir,
        extension: (options.extension ? '.' + options.extension : ''),
        fileHeader:
            '/*\n' +
            ' * Generated by OPRA Service Generator \n' +
            ' * Version: ' + pkgJson.version + '\n' +
            ' * ' + new Date() + '\n' +
            ' */'
      });
      console.log(chalk.greenBright('Completed'));
    });

program.parse(process.argv);
