name: Update Jira Status

on:
  issues:
    types:
      - closed

jobs:
  update_jira_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'     
        
      - name: Install dependencies
        run: |
          npm install axios

      - name: Update Jira status
        run: |
          node update_jira_status.js
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_HOST: 'panates.atlassian.net'
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
