name: Test
on:
  # Can be called from other workflows
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

  # Can be run manually
  workflow_dispatch:

  # on git push
  push:
    branches:
      - main
      - dev
    paths:
      - 'packages/*/src/**'
      - 'packages/*/test/**'
      - 'packages/*/*.{json,js,mjs,cjs}'
      - 'support/test/**'
      - 'jest.*'
      - 'package.json'
      - 'tsconfig*.json'

# Only one run per branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: >
      (github.event_name != 'pull_request' || github.head_ref != 'dev')
      && !contains(github.event.head_commit.message, 'no-test')
    runs-on: ubuntu-latest
    timeout-minutes: 60

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 8.0
          mongodb-replica-set: test-rs

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.2.0
          security-enabled: false

      - name: Run Kafka KRaft Broker
        uses: spicyparrot/kafka-kraft-action@v1.1.3
        with:
          kafka-version: "3.7.0"
          kafka-topics: "feed-cat,1,feed-dog,1,email-channel-1,1,email-channel-2,1,sms-channel-1,1,sms-channel-2,1"

      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup Environment'
        uses: panates/ghac-setup-node@v1
        with:
          node-version: '20.18.1'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install rman
        run: npm install rman -g

      - name: Run qc tests
        run: rman run qc

      - name: Run unit tests
        run: npm run citest
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          KAFKA_BROKER: localhost:9092
          ELASTIC_HOST: http://localhost:9200

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
